--- 
name: Water
bbver: 4.6
sdk: /Users/vidal/code/rho_apps/rhodes
version: 1.2.2
applog: rholog.txt
vendor: rhomobile
iphone: 
  configuration: Debug
  sdk: iphonesimulator3.0
  codesignidentity: 
  entitlements: 
